# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run Puppeteer tests

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  test:
    env:
      SUITE_NAME: demo-suite

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependendencies
      run: npm ci
    - name: Run tests
      run: npm test
    - name: Archive test report
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: "Test report ${{ github.workflow }} #${{ github.run_number }} ${{ github.run_id }}"
        path: report
        retention-days: 14
    - name: Deploy report to GitHub pages
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ always() }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./report
        exclude_assets: './report/*.json'
        destination_dir: report
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
